### ISSUE TITLE
No en-US file template

### ISSUE THREAD

**Issue by Kvasenok** [luandersonn/FluentCast-translations#9]
Since the transltaion is done manually and the base language is supposed to be English, we should have an English translation file with all the strings to use as a template. Currently some translations are marked as 100% but in reality it's less because the translation files don't have all of the strings included in the first place.

**Comment by luandersonn** [comment]
Done

**Comment by Kvasenok** [comment]
Hi @luandersonn 
Sorry for commenting the closed issue, but are you sure this is the correct up-to-date file? My initial issue was with strings for "Multi-window" and "Check for updates daily" buttons as well as "Donate via the Microsoft Store", "Share on social networks" and half of the "About" page. I thought the base English file was supposed to have these strings but I can't find them there.

**Comment by luandersonn** [comment]
@Kvasenok I'll reopen the issue and check this. Thanks

**Comment by luandersonn** [comment]
@Kvasenok Thanks for opening this issue. I think I've found the problem:
![image](https://github.com/luandersonn/FluentCast-translations/assets/30560453/875a706d-ae8f-48d3-be1b-4f64cfbcd00c)
This text is hard-coded instead of using resource files.

**Comment by Kvasenok** [comment]
@luandersonn ah, so that's what it is. Are you planning on adding these strings?

**Comment by luandersonn** [comment]
> @luandersonn ah, so that's what it is. Are you planning on adding these strings?

Yes
